Replace extref only code with P contents extracted from the cp.Raw.
delving/hub3 pull request #66
Opened 2020-12-16 20:56 UTC by scubafly

Replacing the extref only with the stripped / replaced raw p so all types of links can be rendered. And also text outside anchor elements can exist in the P

2020-12-17 09:24 UTC, warmwaterkruik requested changes
Can you please update the CHANGELOG.md file?

2020-12-17 10:19 UTC, warmwaterkruik requested changes
Can you also please update the unit test to reflect the archref, bibref and ref cases in ead_test.go ?
I previously created the test 'Context("for the p in the dsc", func() '

2020-12-17 10:28 UTC, scubafly commented on CHANGELOG.md
> +- Change paragraph's into clevels with and add them to the odd. [[GH-66]](https://github.com/delving/hub3/pull/66)
removed with in new commit.

2020-12-17 12:41 UTC, scubafly commented
Not quite sure all text outside the link elements should end up in the Header.Label[0] see "should have a ref p element" test in ead_test.go

2020-12-21 13:39 UTC, scubafly commented
if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'

2020-12-21 13:43 UTC, scubafly commented
recheckcla

2020-12-21 13:45 UTC, scubafly commented
recheckcla

2020-12-21 13:46 UTC, scubafly commented
recheckcla

2020-12-21 14:13 UTC, warmwaterkruik requested changes

2020-12-22 09:02 UTC, scubafly commented on hub3/ead/ead_test.go
> +				Expect(archref.Header.Label[0]).To(Equal("Let op: deze inventaris is alleen voor het inzien van de dossiers. Kijk in de index voor het zoeken op naam. archref link ."))
Note to compare there needs to be a `.To(Equal()` instead of `==`
Using `==` in an expect will always result in a `TRUE`

I've updated my code.

2020-12-22 09:28 UTC, warmwaterkruik commented on hub3/ead/ead_test.go
> +				Expect(oddString).To(Equal(`<p>Let op: deze inventaris is alleen voor het inzien van de dossiers. Kijk in de index voor het zoeken op naam. ref link <ref linktype="simple" show="new" actuate="onr
The text in the title "Let op: deze inventaris...." is duplicated in the odd. That will come back as an issue. Can't it be removed?

2020-12-22 16:20 UTC, warmwaterkruik commented
Continued in https://github.com/delving/hub3/pull/67

2020-12-22 16:20 UTC, closed without merging